# Generated by Django 2.0.2 on 2021-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210921_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('pianocovers', 'Piano cover'), ('guitarcovers', 'Guitar cover'), ('projects', 'Coding project')], default='pianocover', max_length=50),
        ),
    ]
